captainVersion: 4
services:
    $$cap_appname-wordpress:
        image: wordpress:$$cap_wp_version
        volumes:
            - $$cap_appname-wp-data:/var/www/html
        restart: always
        environment:
            WORDPRESS_DB_HOST: $$cap_db_host:3306
            WORDPRESS_DB_NAME: $$cap_db_name
            WORDPRESS_TABLE_PREFIX: $$cap_db_prefix
            WORDPRESS_DB_USER: $$cap_db_user
            WORDPRESS_DB_PASSWORD: $$cap_db_pass
caproverOneClickApp:
    variables:
        - description: Datenbankhost
          defaultValue: srv-captain--xxx
          id: $$cap_db_host
          label: Datenbankhost
        - description: Database name
          defaultValue: wordpress
          id: $$cap_db_name
          label: DB Name
        - description: Der Tabellenpräfix, der von diesem WordPress verwendet wird.
          defaultValue: WP_
          id: $$cap_db_prefix
          label: Tabellenpräfix
        - id: $$cap_db_user
          label: Datenbankbenutzer
          defaultValue: wordpressuser
        - id: $$cap_db_pass
          label: Datenbankkennwort
          description: ''
          validRegex: /.{1,}/
          defaultValue: $$cap_gen_random_hex(16)
        - id: $$cap_wp_version
          label: WordPress Version
          defaultValue: php8.3-apache
          description: Schau dir ihre Docker-Seite für die gültigen Tags an - https://hub.docker.com/r/library/wordpress/tags/
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            WordPress ist ein Online-Tool zur Website-Erstellung, das in PHP geschrieben ist. In einfachen Worten ausgedrückt, ist es wahrscheinlich das einfachste und leistungsstärkste Blogging- und Content-Management-System (CMS), das es heute gibt.

            Gib deine WordPress-Konfigurationsparameter ein und klicke auf "Weiter". Ein WordPress-Container wird für dich erstellt. Der Prozess dauert etwa eine Minute, bis er abgeschlossen ist.

            Hinweis: Diese App richtet sich an fortgeschrittene Benutzer, die eine zentrale Datenbank in einem einzigen Container für mehrere WordPress-Installationen haben möchten. Du solltest damit beginnen, deine Datenbank zu konfigurieren, und dann mit allen Informationen zur Datenbank zurückkehren.
        end: >-
            WordPress wurde bereitgestellt und ist als $$cap_appname-wordpress verfügbar.

            
            WICHTIG: Es kann bis zu 2 Minuten dauern, bis WordPress bereit ist. Vorher könnte eine 502 Fehlerseite angezeigt werden.

            Denke daran, dass diese App keine Datenbank von selbst erstellen wird. Du musst alle diese Informationen bereitstellen.
    displayName: WordPress - Keine Datenbank
    isOfficial: true
    description: Dies wird nur ein WordPress erstellen. Du musst die Datenbankinformationen manuell erstellen und konfigurieren. Dies ist für fortgeschrittene Benutzer gedacht.
    documentation: Taken from https://docs.docker.com/compose/wordpress/. Port mapping removed from WP as it is no longer needed
